### ISSUE TITLE
Version

### ISSUE THREAD

**Issue by Jelly9912** [SavionLegendZzz/PocketMine-0.13#1]
This is for some build? Or for official version?

**Comment by SavionLegendZzz** [comment]
official version

**Comment by ardaozkal** [comment]
Stop lying please. There is no announcement by the developers and you aren't the developer.

**Comment by Jelly9912** [comment]
I mean version of minecraft lol

**Comment by SavionLegendZzz** [comment]
yes minecraft version

**Comment by Jelly9912** [comment]
I know, it's to ardaozkal

**Comment by ardaozkal** [comment]
oh im an idiot lel
